language: python

install:
    - pip install -r tests/requirements.txt

services:
  - docker

before_script: ./tests/set-up.py "${PG_VERSION}"
script: ./tests/test.py "${PG_VERSION}"
after_script: ./tests/tear-down.py "${PG_VERSION}"

env:
  - PG_VERSION=9.2
  - PG_VERSION=9.3
  - PG_VERSION=9.4
  - PG_VERSION=9.5
  - PG_VERSION=9.6
