language: bash

before_script: ./tests/set-up.sh
script: ./tests/test.sh "${PG_VERSION}"
after_script: ./tests/tear-down.sh

env:
  - PG_VERSION=9.2
  - PG_VERSION=9.3
  - PG_VERSION=9.4
  - PG_VERSION=9.5
  - PG_VERSION=9.6
