language: python

install:
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt
  - pip install pgxnclient
  - pgxn install multicorn
  - python setup.py install

services:
  - postgresql
  - elasticsearch

addons:
  postgresql: "9.5"

script: ./tests/test.py "${PG_VERSION}"

env:
  - PG_VERSION=9.5
