language: python

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq "postgresql-${PG_VERSION}-python-multicorn"
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt
  - python setup.py install

services:
  - postgresql
  - elasticsearch

addons:
  postgresql: "9.5"

script: ./tests/test.py "${PG_VERSION}"

env:
  - PG_VERSION=9.5
