dist: trusty
sudo: required
language: python

install:
  - sudo sh -c 'echo "deb http://gb.archive.ubuntu.com/ubuntu/ xenial main restricted" >> /etc/apt/sources.list.d/xenial.list'
  - sudo apt-get update -qq
  - sudo apt-get install --yes postgresql-9.5-python-multicorn
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt
  - python setup.py install

services:
  - postgresql
  - elasticsearch

addons:
  postgresql: "9.5"

python:
  - "3.6"

script: ./tests/test.py "${PG_VERSION}"

env:
  - PG_VERSION=9.5
